# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-13
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build Intel
      run: GOOS=darwin GOARCH=${{ matrix.arch }} go build -o amialive-${{matrix.arch}} -v ./...

    - name: Test
      run: GOOS=darwin GOARCH=${{ matrix.arch }} go test -v ./...

    - name: Release
      if: github.ref_type == 'tag'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          amialive-${{matrix.arch}}
