# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -o amialive.app -v ./... && chmod 755 ./amialive.app

    - name: Test
      run: go test -v ./...

    - name: Release
      if: github.ref_type == 'tag'
      uses: "softprops/action-gh-release@v2"
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          amialive.app
